### ISSUE TITLE
Problem compiling TensorFlow with Clang via CK

### ISSUE THREAD

**Issue by gfursin** [ctuning/ck-tensorflow#18]
I tried to compile TensorFlow with detected clang 3.8 on my Ubuntu 16.04 with Intel processor but it failed on linking stage when linking protobuf. GCC works fine. If anyone has time to reproduce and fix that, I would appreciate that!

**Comment by Rhymmor** [comment]
Fixed it. #21

**Comment by gfursin** [comment]
Hmm, I still have issues on our velocity server. I updated all repos and when I compile from scratch using 3.8, I still have the same issue with linking protobuf:

/home/fursin/CK/local/env/53614eb6bb79cc97/src/tensorflow/contrib/makefile/gen/lib/libtensorflow-core.a(feature.pb_text.o): In function `tensorflow::internal::AppendProtoDebugString(tensorflow::strings::ProtoTextOutput*, tensorflow::FeatureLists const&)':
/home/fursin/CK/local/env/53614eb6bb79cc97/src/tensorflow/contrib/makefile/gen/proto_text/tensorflow/core/example/feature.pb_text.cc:(.text+0x4b76): undefined reference to `google::protobuf::internal::MapFieldBase::SyncMapWithRepeatedField() const'
/home/fursin/CK/local/env/53614eb6bb79cc97/src/tensorflow/contrib/makefile/gen/proto_text/tensorflow/core/example/feature.pb_text.cc:(.text+0x4d46): undefined reference to `google::protobuf::internal::MapFieldBase::SyncMapWithRepeatedField() const'
/home/fursin/CK/local/env/53614eb6bb79cc97/src/tensorflow/contrib/makefile/gen/lib/libtensorflow-core.a(feature.pb_text.o): In function `tensorflow::internal::ProtoParseFromScanner(tensorflow::strings::Scanner*, bool, bool, tensorflow::FeatureLists*)':
/home/fursin/CK/local/env/53614eb6bb79cc97/src/tensorflow/contrib/makefile/gen/proto_text/tensorflow/core/example/feature.pb_text.cc:(.text+0x538d): undefined reference to `google::protobuf::internal::MapFieldBase::SyncMapWithRepeatedField() const'
/home/fursin/CK/local/env/53614eb6bb79cc97/src/tensorflow/contrib/makefile/gen/proto_text/tensorflow/core/example/feature.pb_text.cc:(.text+0x53a2): undefined reference to `google::protobuf::internal::MapFieldBase::SetMapDirty()'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
tensorflow/contrib/makefile/Makefile:510: recipe for target '/home/fursin/CK/local/env/53614eb6bb79cc97/src/tensorflow/contrib/makefile/gen/bin/benchmark' failed
make: *** [/home/fursin/CK/local/env/53614eb6bb79cc97/src/tensorflow/contrib/makefile/gen/bin/benchmark] Error 1

I invoke the following command:
$ ck install package:lib-tensorflow-cpu-make

and then select LLVM 3.8 compiler ...

**Comment by gfursin** [comment]
This is now working. Thanks!
